### ISSUE TITLE
limitDenominator traps because it tries to create a Rational with a negative denominator

### ISSUE THREAD

**Issue by maartene** [abdel-17/swift-rational#3]
Hi, 

While writing test cases for  I found it traps for instance when using the following example case:

```
let r = Rational(-65799040, 325053649)
print(r.limitDenominator(to: 10_000_000)).    // traps because it tries to create a rational with a negative denominator
```

For comparison: the resulting rational should be `Rational(-233695, 1154476)` (as per Pythons Fraction module)

**Comment by abdel-17** [comment]
Looks like the issue was due to the algorithm being implemented in Python originally, which behaves differently when it comes to integer division. I fixed the issue. Thanks for reporting. 👍🏼
